### ISSUE TITLE
Cannot update quantity in localstorage

### ISSUE THREAD

**Issue by mserr113** [mserr113/P5-Web-Dev-Kanap#1]
cannot figure out how to update quantity in localstorage. It was originally adding the new quantity as a string, so original quantity of 1 would be updated to '11' instead of '2' when I added a quantity of 1 to the cart. I used partInt on the original "quantity" and the "old quantity" so that both are recognized as numbers, but now the localstorage isn't updating at all when I add additional quantity into the cart.

**Comment by AccessiT3ch** [comment]
@mserr113 Looking at your product.js there is one thing that stands out when you're trying to determine if the `searchForItemInLocalStorage` is defined. We actually can't directly compare anything to `undefined`, instead we check the `typeof` our variable to see if it is undefined.

```js
const someDatum = data.find( ... );

if (someDatum === undefined) {
  // this will never be true
  // which is where your arr.push(item) lives
}

if (typeof someDatum === 'undefined') {
  // typeof [var] returns a string of the type,
  // so we have to check if it matches the string "undefined"
  // technically this is probably the best way because it is the most explicit
}

if (!someDatum) {
  // we can also use the ! character to determine if something is "falsey"
  // !true => false
  // !("") => true b/c an empty string is falsey
  // !someUndefinedVar => true
}

**Comment by AccessiT3ch** [comment]
I'm not sure I'm following [this `if/else` statement](https://github.com/mserr113/P5-Web-Dev-Kanap/blob/master/front/js/product.js#L63-L69), it looks like the else block isn't pushing anything to the array before adding the array back into localStorage. In this case I think there's  a few key things to do in else block.

```js
if (typeof searchForItemInLocalStorage === 'undefined') {
  // if the item and color do not exist in the cart array, add it
  cart.push(itemDetails); // which is what you're doing

  // add the old cart with the new item into localStorage
  localStorage.setItem('cart', JSON.stringify(cart));
} else {
  // if the item and color DO exist in the cart

  // 1. define a new array with the match filtered out
  const newCart = cart.filter((x) => x.id === id && x.color === color);

  // 2. Update the quantity on the itemDetails object
  itemDetails.quantity += parseInt(searchForItemInLocalStorage.quantity)

  // 3. Push the updated item into the new cart array
  newCart.push(itemDetails);

  // 4. add the new cart array with the updated item quantity to localStorage
  localStorage.setItem('cart', JSON.stringify(newCart));
}
```

**Comment by AccessiT3ch** [comment]
One last thing, currently [where you're adding your quantities together](https://github.com/mserr113/P5-Web-Dev-Kanap/blob/master/front/js/product.js#L68), you don't want to update the `quantity` constant (really at all), especially after you've assigned its value to the `itemDetails` object.

IF this if currently working, it's only because you're mutating the value of the const, which is then also mutating everything that references it (in this case your `itemDetails` object). In this case that might have the desired effect, but we try very hard to avoid mutations like this as it can make things very buggy and difficult to debug.

In step 2 in the else statement above, we are updating the value of `itemDetails.quantity` in a way that doesn't mutate anything because that line actually breaks the object's reference to the original `quantity` constant.

**Comment by mserr113** [comment]
Thank you! I was trying to mutate, so good to know it can be buggy. I was able to get the filter to update the item quantity!
